/*
 * Copyright (c) 2001-2014, TIBCO Software Inc.
 * Use, modification, and distribution subject to terms of license.
 */
jsx3.require("jsx3.gui.Block");jsx3.Class.defineClass("jsx3.gui.Window",jsx3.app.Model,null,function(a,n){var
ub={A:"onLoad ",B:"unload",C:"onunload",D:"body",E:"head",F:"link",G:"stylesheet",H:"href",I:"id",J:"rel",K:"type",L:'<span id="',M:'"></span>',N:"jsx3",O:"onFocus ",P:"onBeforeUnload ",Q:"function",R:"object",S:"onResize ",T:"onParentUnload",U:"_JSXROOT",V:"100%",W:"jsxbgcolor",X:"@Solid Light",Y:" ",a:"jsx:///../jsx3.gui.window.html",b:"jsx:///../jsx3.gui.window.xhtml",c:"screenLeft",d:"screenTop",e:"screenX",f:"screenY",g:"open",h:"close",i:"focus",j:"resize",k:"pclose",l:"",m:"gui.win.op",n:".xhtml",o:/\./g,p:"directories=no,location=no,menubar=no,status=yes,personalbar=no,titlebar=yes,toolbar=no,width=",q:",",r:"height=",s:"resizable=",t:"yes",u:"no",v:"scrollbars=",w:"_jsxwindow",x:"about:blank",y:"gui.win.rm",z:"gui.win.cl"};var
Y=jsx3.Exception;var
ca=jsx3.util.Logger;var
Ra=ca.getLogger(a.jsxclass.getName());a.LW=jsx3.resolveURI(ub.a);a.KG=jsx3.resolveURI(ub.b);if(jsx3.CLASS_LOADER.IE){a.KL=ub.c;a.xO=ub.d;}else{a.KL=ub.e;a.xO=ub.f;}a.DID_OPEN=ub.g;a.WILL_CLOSE=ub.h;a.DID_FOCUS=ub.i;a.DID_RESIZE=ub.j;a.PARENT_DID_CLOSE=ub.k;n.jsxwidth=400;n.jsxheight=300;n.jsxresizable=0;n.jsxscrollable=0;n.jsxdependent=1;n.jsxtitle=ub.l;n._jsxwindow=null;n._jsxpB=null;n.init=function(b){this.jsxsuper(b);};n.open=function(){if(this._jsxwindow!=null&&!this._jsxwindow.closed){throw new
Y(jsx3._msg(ub.m,this));}else{var
R=jsx3.util.strEndsWith(((jsx3.app.Browser.getLocation()).getPath()).toLowerCase(),ub.n)?a.KG:a.LW;var
tb=window.open(R,(this.getId()).replace(ub.o,ub.l),ub.p+this.getWidth()+ub.q+ub.r+this.getHeight()+ub.q+ub.s+(this.isResizable()?ub.t:ub.u)+ub.q+ub.v+(this.isScrollable()?ub.t:ub.u));if(tb!=null){var
J=this;if(jsx3.CLASS_LOADER.IE)window._getjsxwindow=function(){tb[ub.w]=J;};tb[ub.w]=this;this._jsxwindow=tb;this._jsxpB=window;return true;}else return false;}};n.close=function(){if(this._jsxwindow!=null&&!this._jsxwindow.closed){var
Wa=this._jsxwindow;if(jsx3.CLASS_LOADER.IE)Wa.location=ub.x;var
Xa=this;window.setTimeout(function(){try{Wa.close();}catch(Kb){var
v=jsx3._msg(ub.y,Xa,(jsx3.lang.NativeError.wrap(Kb)).getMessage());Ra.warn(v);}},500);return true;}else throw new
Y(jsx3._msg(ub.z,this));};n.doClose=function(){(this.getRootBlock()).removeChildren();try{this.close();}catch(Kb){var
Z=jsx3._msg(ub.y,this,(jsx3.lang.NativeError.wrap(Kb)).getMessage());Ra.warn(Z);}if(this.getParent())(this.getParent()).removeChild(this);};n.focus=function(){if(this._jsxwindow!=null&&!this._jsxwindow.closed){this._jsxwindow.focus();}else throw new
Y(jsx3._msg(ub.z,this));};n.isOpen=function(){return this._jsxwindow!=null&&!this._jsxwindow.closed;};n.isParentOpen=function(){return this._jsxpB!=null&&!this._jsxpB.closed;};n.moveTo=function(d,r){if(this._jsxwindow!=null&&!this._jsxwindow.closed){if(this._jsxpB!=null&&!this._jsxpB.closed)this._jsxwindow.moveBy(d-this._jsxwindow[a.KL]+this._jsxpB[a.KL],r-this._jsxwindow[a.xO]+this._jsxpB[a.xO]);else this._jsxwindow.moveBy(d-this._jsxwindow[a.KL],r-this._jsxwindow[a.xO]);}else throw new
Y(jsx3._msg(ub.z,this));};n.constrainToScreen=function(){if(this._jsxwindow!=null&&!this._jsxwindow.closed){var
lb=this._jsxwindow;if(lb[a.KL]<0||lb[a.KL]>window.screen.width||lb[a.xO]<0||lb[a.xO]>window.screen.height)lb.moveTo(0,0);}};n.getOffsetLeft=function(){if(this._jsxwindow!=null&&!this._jsxwindow.closed){if(this._jsxpB!=null&&!this._jsxpB.closed)return this._jsxwindow[a.KL]-this._jsxpB[a.KL];else return this._jsxwindow[a.KL];}else throw new
Y(jsx3._msg(ub.z,this));};n.getOffsetTop=function(){if(this._jsxwindow!=null&&!this._jsxwindow.closed){if(this._jsxpB!=null&&!this._jsxpB.closed)return this._jsxwindow[a.xO]-this._jsxpB[a.xO];else return this._jsxwindow[a.xO];}else throw new
Y(jsx3._msg(ub.z,this));};n.onunload=function(){if(this.isDependent()&&this._jsxwindow&&this._jsxwindow.close)try{this._jsxwindow.close();}catch(Kb){}};n.onLoad=function(s){if(Ra.isLoggable(5))Ra.debug(ub.A+this);jsx3.gui.Event.subscribe(ub.B,this,ub.C);jsx3.gui.Event._registerWindow(s);var
tb=s.document;var
za=s.opener;var
pb=(tb.getElementsByTagName(ub.D))[0];var
bb=(tb.getElementsByTagName(ub.E))[0];var
L=(this.getServer()).getRootDocument();var
G=L.getElementsByTagName(ub.F);for(var
R=0;R<G.length;R++){var
Ba=G[R];if(Ba.rel==ub.G){var
aa=Ba.getAttribute(ub.H);var
Ma=tb.createElement(ub.F);Ma.setAttribute(ub.I,Ba.getAttribute(ub.I));Ma.setAttribute(ub.H,aa);Ma.setAttribute(ub.J,Ba.getAttribute(ub.J));Ma.setAttribute(ub.K,Ba.getAttribute(ub.K));bb.appendChild(Ma);}}pb.innerHTML=ub.L+(this.getRootBlock()).getId()+ub.M;(this.getRootBlock()).repaint();s[ub.N]=za.jsx3;this._jsxwindow=s;this._jsxpB=za;this.setTitle(this.getTitle());this.publish({subject:ub.g});};n.onFocus=function(){if(Ra.isLoggable(5))Ra.debug(ub.O+this);this.publish({subject:ub.i});};n.onBeforeUnload=function(){if(Ra.isLoggable(5))Ra.debug(ub.P+this);try{jsx3.gui.Event.unsubscribe(ub.B,this,ub.C);}catch(Kb){}if(jsx3.gui.Event._isWindowRegistered(this._jsxwindow)){jsx3.gui.Event._deregisterWindow(this._jsxwindow);this._jsxwindow.document.onkeydown=null;if(!jsx3.CLASS_LOADER.IE)for(var _ in this._jsxwindow)try{if(typeof this._jsxwindow[_]==ub.Q||typeof this._jsxwindow[_]==ub.R)this._jsxwindow[_]=null;}catch(Kb){}if(this._jsxpB!=null&&!this._jsxpB.closed)this._jsxpB.focus();this._jsxwindow=null;this._jsxpB=null;this.publish({subject:ub.h});}};n.onResize=function(){if(Ra.isLoggable(6))Ra.trace(ub.S+this);this.jsxwidth=this._jsxwindow.document.body.clientWidth;this.jsxheight=this._jsxwindow.document.body.clientHeight;if(this._jsxD3!=null)this._jsxwindow.clearTimeout(this._jsxD3);var
ea=this;this._jsxD3=this._jsxwindow.setTimeout(function(){ea._jsxD3=null;jsx3.gui.Painted.Queue.enableChunking(false);(ea.getRootBlock()).Mc({parentwidth:ea.getWidth(),parentheight:ea.getHeight()},true);jsx3.gui.Painted.Queue.enableChunking(true);},250);this.publish({subject:ub.j});};n.onParentUnload=function(){if(Ra.isLoggable(5))Ra.debug(ub.T);this.publish({subject:a.DID_PARENT_CLOSE});};n.getRootBlock=function(){var
ab=this.getChild(0);if(ab==null){ab=new
jsx3.gui.Block(this.getName()+ub.U,0,0,ub.V,ub.V,ub.l);ab.setDynamicProperty(ub.W,ub.X);ab.setRelativePosition(0);ab.setOverflow(2);ab.setIndex(0);this.setChild(ab);}return ab;};n.getWindow=function(){if(this._jsxwindow!=null&&!this._jsxwindow.closed)return this._jsxwindow;return null;};n.getParentWindow=function(){if(this._jsxpB!=null&&!this._jsxpB.closed)return this._jsxpB;return null;};n.getDocument=function(){if(this._jsxwindow!=null&&!this._jsxwindow.closed)return this._jsxwindow.document;return null;};n.Id=function(){return {parentwidth:this.getWidth(),parentheight:this.getHeight()};};n.repaint=function(){return (this.getRootBlock()).repaint();};n.getWidth=function(){return this.jsxwidth;};n.setWidth=function(q){if(this._jsxwindow!=null&&!this._jsxwindow.closed)this._jsxwindow.resizeBy(q-this.jsxwidth,0);this.jsxwidth=q;};n.getHeight=function(){return this.jsxheight;};n.setHeight=function(l){if(this._jsxwindow!=null&&!this._jsxwindow.closed)this._jsxwindow.resizeBy(0,l-this.jsxheight);this.jsxheight=l;};n.isResizable=function(){return this.jsxresizable;};n.setResizable=function(j){this.jsxresizable=jsx3.Boolean.valueOf(j);};n.isScrollable=function(){return this.jsxscrollable;};n.setScrollable=function(o){this.jsxscrollable=jsx3.Boolean.valueOf(o);};n.isDependent=function(){return this.jsxdependent;};n.setDependent=function(p){this.jsxdependent=jsx3.Boolean.valueOf(p);};n.getTitle=function(){return this.jsxtitle;};n.setTitle=function(m){this.jsxtitle=m;if(this._jsxwindow!=null&&!this._jsxwindow.closed)this._jsxwindow.document.title=m;};n.toString=function(p){return this.jsxsuper()+ub.Y+this.getName();};});
